### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by deadtrickster** [alesasnouski/prom_plugs_app#1]
I'll continue here if you don't mind.

1) What I have right now is 2/4 I7 4510U. I don't have access to bigger machines.
2) I had to disable logging with.

``` elixir
config :logger,
  level: :warn
```

3) We still test the complete stack - Cowboy, Plugs. Not Prometheus.erl itself.

I wasn't able to reproduce your results (I think because of 1)).

```
Plugs Commented

Running 30s test @ http://localhost:8088/profiles/1/
  16 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    44.84ms    6.27ms 139.57ms   81.57%
    Req/Sec   358.42     32.84     0.89k    79.78%
  171456 requests in 30.10s, 43.69MB read
Requests/sec:   5696.98
Transfer/sec:      1.45MB


Uncommented

Running 30s test @ http://localhost:8088/profiles/1/
  16 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    45.63ms    6.07ms 252.06ms   79.92%
    Req/Sec   351.83     30.33   515.00     76.99%
  168375 requests in 30.09s, 42.90MB read
Requests/sec:   5595.81
Transfer/sec:      1.43MB
```

I had a test code a-la https://github.com/jlouis/fuse/blob/master/stress/stress.erl but well, lost it :-). Few thoughts though:
- ETS backend scales (in terms of 'client' processes count) bad when you just have one metric you constantly increment. Which is understandable since `write_concurrency` optimization won't work for single ETS table item;
  - ETS scales when many client processes work with many different metrics (thanks to `write_concurrency`);
  - You can get smaller latency with d-functions and `call_timeout` set to `false` essentially forcing `gen_server:cast` but as I mentioned on Twitter queues can be overflowed and moreover it could make calculating rates on Prometheus side useless because queue smooths peaks.

**Comment by alesasnouski** [comment]
This issue is not reproducible on desktop machines, everything is ok on my core i7 4790k (8ht cores). But synchronous writes to ets becomes a bottleneck on real production systems... Thank you.

**Comment by deadtrickster** [comment]
I hope that not turned you away from the library. I'd like to continue this discussion and probably we can make prometheus.erl better.

How accurately your test code reflects your real code? Can you rewrite it using d-functions and somehow monitor queues length?

**Comment by deadtrickster** [comment]
I've implemented scheduler pinning: https://github.com/deadtrickster/prometheus.erl/tree/ets_schedulers

Benchmarking on fresh c3.8xlarge. Benchmark isolates prometheus.erl and enforces the worst case for ETS - many processes increment the same counter. 

Master:

```
1> c("benchmark.erl").
{ok,benchmark}
2> benchmark:run(1, 1*1000*1000).
{272271,1000000}
3> benchmark:run(3, 1*1000*1000).
{569218,3000000}
4> benchmark:run(4, 1*1000*1000).
{10658833,4000000}
5> benchmark:run(5, 1*1000*1000).
{58670268,5000000}
6> benchmark:run(10, 1*1000*1000).
{119126705,10000000}
7> benchmark:run(100, 1*1000*1000).
{1190646707,100000000}
```

ets_schedulers branch:

```
1> c("benchmark").
{ok,benchmark}
2> benchmark:run(1, 1*1000*1000).
{302470,1000000}
3> benchmark:run(3, 1*1000*1000).
{329957,3000000}
4> benchmark:run(4, 1*1000*1000).
{306236,4000000}
5> benchmark:run(5, 1*1000*1000).
{307977,5000000}
6> benchmark:run(10, 1*1000*1000).
{481469,10000000}
7> benchmark:run(100, 1*1000*1000).
{2590239,100000000}
```

Time is in microseconds, VM args - +S 16:16.

Wrk result hasn't changed much - around 39000 req/s.

Please do let me know if you'll see any difference on your setup.

**Comment by alesasnouski** [comment]
Wow, that was really fast. I didn't have enough time to dive deep into your changes, but result is good: 
**Before:** 

```
~/wrk/wrk -d30s -c256 -t16 http://localhost:8088/profiles/1/
Running 30s test @ http://localhost:8088/profiles/1/
  16 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.05ms    1.91ms  32.67ms   72.76%
    Req/Sec     2.00k   398.69    17.21k    89.42%
  954547 requests in 30.10s, 243.23MB read
Requests/sec:  31712.45
Transfer/sec:      8.08MB
```

**After**:

```
~/wrk/wrk -d30s -c256 -t16 http://localhost:8088/profiles/1/
Running 30s test @ http://localhost:8088/profiles/1/
  16 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.65ms    1.12ms  50.43ms   87.19%
    Req/Sec     3.47k   382.68     9.47k    83.69%
  1659848 requests in 30.10s, 422.95MB read
Requests/sec:  55146.19
```

Transfer/sec:     14.05MB
![prometheus_master](https://cloud.githubusercontent.com/assets/223009/19016411/6aba7074-8821-11e6-8b6a-b5c33dca26d4.png)
![branch_ets_schedulers](https://cloud.githubusercontent.com/assets/223009/19016412/6ea8f246-8821-11e6-9fb3-1e9f716505ae.png)

Now cpu is 100% utilized. Is it possible to include merge your changes into master?

**Comment by alesasnouski** [comment]
Thank you! :)

**Comment by deadtrickster** [comment]
I'm rewriting benchmarks into tests. I want to make sure everything calculated right even when concurrency level is high. 

I observed that both wrk and ab report different requests count than prometheus counter/histogram if requests count isn't limited explicitly:

``` elixir
## ab -n 100000 -c 10 http://localhost:8088/profiles/1/
## Finished 100000 requests

iex(3)> :prometheus_counter.value(:http_requests_total, [200, "GET", "get_profile"])
100000
iex(2)> {buckets, sum} = :prometheus_histogram.value(:http_request_duration_microseconds, [200, "GET", "get_profile"])
{[33722, 59138, 4685, 1505, 554, 302, 51, 40, 3, 0, 0, 0, 0, 0, 0],
 154257675.015}
iex(3)> :lists.sum(buckets) 
100000

## ab -c 1000 -t 10 http://localhost:8088/profiles/1/
## Finished 34470 requests

iex(1)> :prometheus_counter.value(:http_requests_total, [200, "GET", "get_profile"])
34729
iex(2)> {buckets, sum} = :prometheus_histogram.value(:http_request_duration_microseconds, [200, "GET", "get_profile"])
{[1283, 5109, 7032, 5977, 4415, 5879, 1850, 1198, 998, 976, 12, 0, 0, 0,
  0], 345773649.302}
iex(3)> :lists.sum(buckets) 
34729

## wrk -d30s -c256 -t16 http://localhost:8088/profiles/1/
## 144275 requests in 30.10s, 36.76MB read

iex(1)> :prometheus_counter.value(:http_requests_total, [200, "GET", "get_profile"])
144514
iex(2)> {buckets, sum} = :prometheus_histogram.value(:http_request_duration_microseconds, [200, "GET", "get_profile"])
{[4, 14, 17, 8, 2, 10, 24, 90, 78140, 66057, 148, 0, 0, 0, 0],
 7366531694.549}
iex(3)> :lists.sum(buckets) 
144514

```

The same with Elli server (and master/ets_schedulers branches of prometheus):

```
wrk: 7623 requests 
4> prometheus_counter:value(http_requests_total, ['GET',<<"hello">>,"success"]).
7879
```

See? counts match only when I explicitly tell ab how many requests should go. In the other cases actual counters are slightly higher. I have no idea why, Thoughts?

**Comment by alesasnouski** [comment]
Nginx can proxify, log and count ...

**Comment by deadtrickster** [comment]
using ngxtop:

wrk: 318483 requests in 30.09s, 104.27MB read
ngxtop: 318675

So I guess it's ok...

I'll ping you after merge.

**Comment by deadtrickster** [comment]
merged
